# Generated by Django 4.2 on 2023-04-25 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgvote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgvote.survey'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgvote.topic'),
        ),
    ]
