# Generated by Django 4.2 on 2023-04-25 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgvote', '0002_alter_question_survey_alter_survey_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='name',
            new_name='organization_text',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='name',
            new_name='survey_text',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='name',
            new_name='topic_text',
        ),
    ]
