# Generated by Django 4.2 on 2023-04-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgvote', '0003_rename_name_organization_organization_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='organization_text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='survey_text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic_text',
            new_name='name',
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='question', max_length=50),
        ),
    ]
