# Generated by Django 4.2 on 2023-04-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgvote', '0006_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
