# Generated by Django 4.2 on 2023-05-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgvote', '0008_organization_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
