# Generated by Django 4.2 on 2023-05-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgvote', '0009_topic_pub_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
